force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <description>List of unique dealer codes created from premise codes in user object</description>
    <label>Dealer</label>
    <nameField>
        <label>Dealer Premise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>Dealer code</description>
    <externalId>true</externalId>
    <label>Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Premise_Code__c.field-meta.xml
<CustomField>
    <fullName>Premise_Code__c</fullName>
    <description>Contains the Premise code used by a Telstra Store. This used to facilitate Role Hierarchy in Salesforce.</description>
    <inlineHelpText>Contains the Premise code used by a Telstra Store. This used to facilitate Role Hierarchy in Salesforce.</inlineHelpText>
    <label>Premise Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Primary_Premise_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Premise_Name__c</fullName>
    <label>Primary Premise Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PopulateDealerCodesBatch.cls
global class PopulateDealerCodesBatch implements Database.Batchable<sObject>, Database.Stateful {
    String query = 'SELECT Premise_Code__c,Primary_Premise_Name__c FROM User WHERE Premise_Code__c != null';
    global Map<String, String> dealers = new Map<String, String>();
    global integer partnerUsers = 0;
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<sObject> scope){
    	partnerUsers += scope.size();    
        for (User u: (List<User>) scope) {
            dealers.put(u.Premise_Code__c, u.Primary_Premise_Name__c);
        }
    }
    
    public void finish(Database.BatchableContext BC){
    	List<Dealer__c> ds = new List<Dealer__c>();
        for (String code : dealers.keySet()) {
            Dealer__c d = new Dealer__c();
            d.Code__c = code;
            d.Name = dealers.get(code) + ' (' + code + ')';
            ds.add(d);
        }
        try {
    		upsert ds Code__c;
		} catch (DmlException e) {
    		// Process exception here
		}
        system.debug('Number of partner users are ' + partnerUsers) ; 
        system.debug('Number of unique dealers are ' + ds.size()); 
    }
}